################################################################################
#
# Copyright (C) 2006 - 2008 Olux Organization All rights reserved.
# Authors: Merck Hung <merck@olux.org>
#
# File: Makefile
# Description:
#   None
#
################################################################################


kobjs-$(CONFIG_ARCH_IA32)	+=	handler.o
kobjs-$(CONFIG_ARCH_IA32)	+=	interrupt.o
kobjs-$(CONFIG_ARCH_IA32)	+=	krn.o
kobjs-$(CONFIG_ARCH_IA32)	+=	page.o
kobjs-$(CONFIG_ARCH_IA32)	+=	setup.o
kobjs-$(CONFIG_ARCH_IA32)	+=	task.o


