################################################################################
#
# Copyright (C) 2006 - 2008 Olux Organization All rights reserved.
# Authors: Merck Hung <merck@olux.org>
#
# File: Makefile
# Description:
#   None
#
################################################################################


kobjs-$(CONFIG_ARCH_IA32)	+=	console.o
kobjs-$(CONFIG_ARCH_IA32)	+=	menu.o
kobjs-$(CONFIG_ARCH_IA32)	+=	sercon.o
kobjs-$(CONFIG_ARCH_IA32)	+=	ksh.o


