#!/usr/bin/env python3
# Adapted from github.com/merckhung/twn_election (Apache-2.0; see LICENSE.twn_election).
"""Generates third_party/skia/skia_srcs.bzl from a Skia checkout's gn/*.gni files.

Skia exports its source lists as simple GN list assignments. This script
evaluates them (they are a strict subset of GN that maps onto Python) and
writes the subset needed by the CPU-raster + FreeType build used here.

Usage: tools/gen_skia_srcs.py /path/to/skia > third_party/skia/skia_srcs.bzl
"""
import os
import re
import sys

GNI_FILES = [
    "core.gni", "sksl.gni", "utils.gni", "ports.gni", "effects.gni",
    "effects_imagefilters.gni", "opts.gni", "pathops.gni", "codec.gni",
]

# (bzl name, list of gni variables concatenated)
EXPORTS = [
    ("SKIA_PUBLIC_HDRS", [
        "skia_core_public", "skia_utils_public", "skia_effects_public",
        "skia_effects_imagefilter_public", "skia_pathops_public",
        "skia_encode_public", "skia_codec_public",
        "skia_ports_fontmgr_directory_public",
        "skia_ports_fontmgr_empty_public",
    ]),
    ("SKIA_SRCS", [
        "skia_core_sources", "skia_utils_private", "skia_effects_sources",
        "skia_colorfilters_sources", "skia_effects_imagefilter_sources",
        "skia_pathops_sources", "skia_sksl_core_sources",
        "skia_sksl_core_module_sources", "skia_sksl_tracing_sources",
        "skia_ports_sources", "skia_ports_freetype_sources",
        "skia_ports_fontmgr_custom_sources",
        "skia_ports_fontmgr_directory_sources",
        "skia_ports_fontmgr_empty_sources",
        "skia_encode_srcs", "skia_no_encode_jpeg_srcs",
        "skia_no_encode_png_srcs", "skia_no_encode_webp_srcs",
        "skia_codec_shared", "skia_codec_decode_bmp",
    ]),
    ("SKIA_OPTS_ML3_SRCS", ["ml3"]),
    ("SKIA_OPTS_ML4_SRCS", ["ml4"]),
]

EXTRA_SRCS = [
    "src/ports/SkDiscardableMemory_none.cpp",
    "src/ports/SkMemory_malloc.cpp",
    "src/ports/SkOSFile_posix.cpp",
    "src/ports/SkLog_stdio.cpp",
    "src/sfnt/SkOTTable_name.cpp",
    "src/sfnt/SkOTUtils.cpp",
]


def evaluate(skia_root):
    env = {}
    for name in GNI_FILES:
        with open(os.path.join(skia_root, "gn", name)) as f:
            text = f.read()
        lines = []
        for line in text.splitlines():
            stripped = line.split("#", 1)[0].rstrip()
            if "get_path_info" in stripped or stripped.startswith("import("):
                continue
            lines.append(stripped)
        code = "\n".join(lines)
        code = re.sub(r"\$_(src|include|experimental|rust)", r"\1", code)
        # GN scopes ({ ... }) only appear for skia_opts; skip them.
        code = re.sub(r"^\w+\s*=\s*\{.*?^\}", "", code, flags=re.S | re.M)
        # Join GN continuation lines ("x =\n    [ ... ]").
        code = re.sub(r"=\s*\n\s*", "= ", code)
        code = code.replace("true", "True").replace("false", "False")
        exec(compile(code, name, "exec"), {}, env)
    return env


def main():
    skia_root = sys.argv[1]
    env = evaluate(skia_root)
    out = ["# GENERATED by tools/gen_skia_srcs.py -- do not edit.", ""]
    exclude = set(env.get("skia_clipstack_utils_sources", []))
    for bzl_name, gn_vars in EXPORTS:
        files = []
        for var in gn_vars:
            for f in env[var]:
                if f not in files and (bzl_name != "SKIA_SRCS" or f not in exclude):
                    files.append(f)
        if bzl_name == "SKIA_SRCS":
            files += [f for f in EXTRA_SRCS if f not in files]
        files = [f for f in files if os.path.exists(os.path.join(skia_root, f))]
        out.append("%s = [" % bzl_name)
        out += ['    "%s",' % f for f in files]
        out += ["]", ""]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
