#!/usr/bin/env python3
"""Fetch BCR modules through git when their source archives are unreachable.

Some networks allow `git clone` from GitHub but block archive downloads
(github.com/.../archive/..., codeload.github.com, savannah mirrors), which
breaks the Bazel Central Registry modules that point at such archives. This
script clones those modules at the tag or commit the BCR release was made
from, applies the BCR's patches and overlay files (checking their SHA-256
integrity against the registry), copies the registry's MODULE.bazel, and
writes `--override_module` lines to user.bazelrc (untracked, imported by
.bazelrc).

    tools/git_modules.py [--cache DIR] [--registry URL]

Only needed on such networks; normally Bazel fetches everything itself.
"""

import argparse
import base64
import hashlib
import json
import os
import subprocess
import sys
import urllib.request

REGISTRY = "https://raw.githubusercontent.com/bazelbuild/bazel-central-registry/main"

# module, version (as resolved by `bazel mod graph`), git remote, ref
MODULES = [
    ("vulkan_headers", "1.4.349", "https://github.com/KhronosGroup/Vulkan-Headers", "v1.4.349"),
    ("stb", "0.0.0-20251026-f1c79c0", "https://github.com/nothings/stb",
     "f1c79c02822848a9bed4315b12c8c8f3761e1296"),
    ("freetype", "2.14.1.bcr.1", "https://github.com/freetype/freetype", "VER-2-14-1"),
    ("libpng", "1.6.44", "https://github.com/pnggroup/libpng", "v1.6.44"),
]


def fetch(url):
    with urllib.request.urlopen(url, timeout=60) as r:
        return r.read()


def check_sri(data, sri, what):
    algo, _, b64 = sri.partition("-")
    digest = hashlib.new(algo, data).digest()
    if base64.b64encode(digest).decode() != b64:
        sys.exit("integrity mismatch for %s" % what)


def git(*args, cwd=None):
    subprocess.run(["git", *args], cwd=cwd, check=True, stdout=subprocess.DEVNULL)


def prepare(cache, registry, name, version, remote, ref):
    base = "%s/modules/%s/%s" % (registry, name, version)
    dest = os.path.join(cache, "%s-%s" % (name, version))
    stamp = os.path.join(dest, ".git_modules_done")
    if os.path.exists(stamp):
        return dest
    if os.path.exists(dest):
        subprocess.run(["rm", "-rf", dest], check=True)
    os.makedirs(dest)
    git("init", "-q", cwd=dest)
    git("fetch", "-q", "--depth", "1", remote, ref, cwd=dest)
    git("checkout", "-q", "FETCH_HEAD", cwd=dest)
    source = json.loads(fetch(base + "/source.json"))
    for patch, sri in sorted(source.get("patches", {}).items()):
        data = fetch("%s/patches/%s" % (base, patch))
        check_sri(data, sri, patch)
        subprocess.run(["patch", "-s", "-p%d" % source.get("patch_strip", 0)], input=data,
                       cwd=dest, check=True)
    for path, sri in source.get("overlay", {}).items():
        data = fetch("%s/overlay/%s" % (base, path))
        check_sri(data, sri, path)
        os.makedirs(os.path.dirname(os.path.join(dest, path)) or dest, exist_ok=True)
        with open(os.path.join(dest, path), "wb") as f:
            f.write(data)
    with open(os.path.join(dest, "MODULE.bazel"), "wb") as f:
        f.write(fetch(base + "/MODULE.bazel"))
    open(stamp, "w").close()
    return dest


def main():
    here = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache", default=os.path.expanduser("~/.cache/bootviz-modules"))
    ap.add_argument("--registry", default=REGISTRY)
    args = ap.parse_args()
    lines = ["# Generated by tools/git_modules.py: BCR modules fetched with git."]
    for name, version, remote, ref in MODULES:
        path = prepare(args.cache, args.registry, name, version, remote, ref)
        print("%s@%s -> %s" % (name, version, path))
        lines.append("common --override_module=%s=%s" % (name, path))
    with open(os.path.join(here, "user.bazelrc"), "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote user.bazelrc")


if __name__ == "__main__":
    main()
