// Adapted from github.com/merckhung/twn_election (Apache-2.0; see LICENSE.twn_election).
// Embeds SPIR-V binaries into a C++ header/source pair.
//
// Usage: embed_spirv --namespace=ns --header=out.h --source=out.cc
//                    --include=pkg/out.h a.spv b.spv
// Each input `foo.vert.spv` becomes `std::span<const uint32_t> ns::foo_vert()`.

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <cctype>
#include <fstream>
#include <iterator>
#include <string>
#include <vector>

namespace {

std::string Identifier(const std::string& path) {
  std::string base = path.substr(path.find_last_of('/') + 1);
  if (base.size() > 4 && base.compare(base.size() - 4, 4, ".spv") == 0) {
    base.resize(base.size() - 4);
  }
  for (char& c : base) {
    if (!isalnum(static_cast<unsigned char>(c))) c = '_';
  }
  return base;
}

bool StartsWith(const std::string& s, const std::string& prefix) {
  return s.compare(0, prefix.size(), prefix) == 0;
}

}  // namespace

int main(int argc, char** argv) {
  std::string ns = "shaders", header, source, include;
  std::vector<std::string> inputs;
  for (int i = 1; i < argc; ++i) {
    std::string arg = argv[i];
    if (StartsWith(arg, "--namespace=")) {
      ns = arg.substr(12);
    } else if (StartsWith(arg, "--header=")) {
      header = arg.substr(9);
    } else if (StartsWith(arg, "--include=")) {
      include = arg.substr(10);
    } else if (StartsWith(arg, "--source=")) {
      source = arg.substr(9);
    } else {
      inputs.push_back(arg);
    }
  }
  if (header.empty() || source.empty()) {
    std::fprintf(stderr, "embed_spirv: --header and --source are required\n");
    return 1;
  }

  std::ofstream h(header), cc(source);
  if (include.empty()) include = header.substr(header.find_last_of('/') + 1);
  h << "// Generated by embed_spirv. Do not edit.\n#pragma once\n\n"
    << "#include <cstdint>\n#include <span>\n\nnamespace " << ns << " {\n\n";
  cc << "// Generated by embed_spirv. Do not edit.\n#include \"" << include << "\"\n\n"
     << "namespace " << ns << " {\n\n";

  for (const std::string& in : inputs) {
    std::ifstream f(in, std::ios::binary);
    std::vector<char> bytes((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
    if (bytes.empty() || bytes.size() % 4 != 0) {
      std::fprintf(stderr, "embed_spirv: %s is not a SPIR-V module\n", in.c_str());
      return 1;
    }
    const std::string id = Identifier(in);
    h << "std::span<const uint32_t> " << id << "();\n";
    cc << "static const uint32_t k_" << id << "[] = {";
    for (size_t i = 0; i < bytes.size(); i += 4) {
      uint32_t w;
      std::memcpy(&w, &bytes[i], 4);
      if ((i / 4) % 8 == 0) cc << "\n   ";
      char buf[16];
      std::snprintf(buf, sizeof buf, " 0x%08x,", w);
      cc << buf;
    }
    cc << "\n};\nstd::span<const uint32_t> " << id << "() { return k_" << id << "; }\n\n";
  }
  h << "\n}  // namespace " << ns << "\n";
  cc << "}  // namespace " << ns << "\n";
  return 0;
}
