################################################################################
#
# Copyright (C) 2006 - 2008 Olux Organization All rights reserved.
# Authors: Merck Hung <merck@olux.org>
#
# File: Makefile
# Description:
#   None
#
################################################################################


kobjs-$(CONFIG_ARCH_IA32)	+=	console
kobjs-$(CONFIG_ARCH_IA32)	+=	framebuffer
kobjs-$(CONFIG_ARCH_IA32)	+=	ide
kobjs-$(CONFIG_ARCH_IA32)	+=	input
kobjs-$(CONFIG_ARCH_IA32)	+=	pci
kobjs-$(CONFIG_ARCH_IA32)	+=	resource
kobjs-$(CONFIG_ARCH_IA32)	+=	serial


