#!/usr/bin/env bash
###############################################################################
# OluxOS userspace toolchain builder (offline, reproducible)
#
# Builds, from the source tarballs vendored in third_party/:
#   1. musl libc (static)           -> $OUT/sysroot/{include,lib}
#   2. a compiler wrapper            -> $OUT/bin/oluxos-cc
#   3. BusyBox (static, musl-linked) -> $OUT/bin/busybox
#   4. Dropbear SSH (static)         -> $OUT/bin/dropbearmulti
#
# The only host requirement is an AArch64 GCC cross compiler + binutils:
#   * Debian/Ubuntu:  apt install gcc-aarch64-linux-gnu      (prefix aarch64-linux-gnu-)
#   * or build one from source with toolchains/cross/build-cross-gcc.sh
#     (prefix aarch64-linux-musl-, installed under toolchains/cross/install)
#
# Usage:
#   toolchains/userspace/build.sh [--out DIR] [--cross PREFIX] [--jobs N]
#                                 [musl|busybox|dropbear|all]
#
# Environment overrides: OLUXOS_CROSS (compiler prefix), OUT, JOBS.
###############################################################################
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

MUSL_VERSION=1.2.5
MUSL_TARBALL="$REPO_ROOT/third_party/musl/musl-${MUSL_VERSION}.tar.gz"
MUSL_SHA256=a9a118bbe84d8764da0ea0d28b3ab3fae8477fc7e4085d90102b8596fc7c75e4

BUSYBOX_VERSION=1.36.1
BUSYBOX_TARBALL="$REPO_ROOT/third_party/busybox/busybox-${BUSYBOX_VERSION}.tar.bz2"
BUSYBOX_SHA256=b8cc24c9574d809e7279c3be349795c5d5ceb6fdf19ca709f80cde50e47de314
BUSYBOX_CONFIG="$REPO_ROOT/toolchains/userspace/busybox.config"
BUSYBOX_PATCHES="$REPO_ROOT/toolchains/userspace/patches/busybox"

DROPBEAR_VERSION=2024.86
DROPBEAR_TARBALL="$REPO_ROOT/third_party/dropbear/dropbear-${DROPBEAR_VERSION}.tar.bz2"
DROPBEAR_SHA256=f933205a1e98b98810fcc5116cf97bdb6065c28bad526ff42f7eaf1bd2943ea6

OUT="${OUT:-$REPO_ROOT/toolchains/userspace/out}"
JOBS="${JOBS:-$(nproc 2>/dev/null || echo 4)}"
CROSS="${OLUXOS_CROSS:-}"
TARGET=all

while [ $# -gt 0 ]; do
  case "$1" in
    --out) OUT="$2"; shift 2 ;;
    --cross) CROSS="$2"; shift 2 ;;
    --jobs) JOBS="$2"; shift 2 ;;
    musl|busybox|dropbear|all) TARGET="$1"; shift ;;
    -h|--help) sed -n '2,22p' "$0"; exit 0 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

log() { printf '[userspace] %s\n' "$*" >&2; }
die() { printf '[userspace] ERROR: %s\n' "$*" >&2; exit 1; }

# Pick a cross compiler: explicit > in-tree built > host package.
if [ -z "$CROSS" ]; then
  if [ -x "$REPO_ROOT/toolchains/cross/install/bin/aarch64-linux-musl-gcc" ]; then
    CROSS="$REPO_ROOT/toolchains/cross/install/bin/aarch64-linux-musl-"
  elif command -v aarch64-linux-gnu-gcc >/dev/null 2>&1; then
    CROSS=aarch64-linux-gnu-
  elif command -v aarch64-linux-musl-gcc >/dev/null 2>&1; then
    CROSS=aarch64-linux-musl-
  else
    die "no AArch64 cross compiler found; install gcc-aarch64-linux-gnu or run toolchains/cross/build-cross-gcc.sh"
  fi
fi
command -v "${CROSS}gcc" >/dev/null 2>&1 || die "${CROSS}gcc not found"

verify() {
  local file="$1" want="$2" got
  [ -f "$file" ] || die "missing $file"
  got="$(sha256sum "$file" | cut -d' ' -f1)"
  [ "$got" = "$want" ] || die "checksum mismatch for $file (got $got)"
}

mkdir -p "$OUT"
OUT="$(cd "$OUT" && pwd)"
WORK="$OUT/work"
SYSROOT="$OUT/sysroot"
mkdir -p "$WORK" "$OUT/bin"

# Deterministic output: fixed timestamps, no host paths in debug info.
export SOURCE_DATE_EPOCH="${SOURCE_DATE_EPOCH:-1700000000}"
export LC_ALL=C TZ=UTC

build_musl() {
  if [ -f "$SYSROOT/lib/libc.a" ] && [ -f "$SYSROOT/.stamp-$MUSL_VERSION" ]; then
    log "musl $MUSL_VERSION already built"
    return
  fi
  verify "$MUSL_TARBALL" "$MUSL_SHA256"
  log "building musl $MUSL_VERSION with ${CROSS}gcc"
  rm -rf "$WORK/musl-$MUSL_VERSION" "$SYSROOT"
  tar -xzf "$MUSL_TARBALL" -C "$WORK"
  (
    cd "$WORK/musl-$MUSL_VERSION"
    CC="${CROSS}gcc" AR="${CROSS}ar" RANLIB="${CROSS}ranlib" \
      CFLAGS="-O2 -ffile-prefix-map=$WORK=." \
      ./configure --target=aarch64-linux-musl --prefix="$SYSROOT" \
        --syslibdir="$SYSROOT/lib" --disable-shared >/dev/null
    make -j"$JOBS" >/dev/null
    make install >/dev/null
  )
  touch "$SYSROOT/.stamp-$MUSL_VERSION"
}

# musl-gcc style wrapper that works with any cross GCC, using the sysroot's
# own headers and startup files and the compiler's libgcc.
write_wrapper() {
  local libgcc
  libgcc="$("${CROSS}gcc" -print-libgcc-file-name)"
  cat >"$OUT/bin/oluxos-cc" <<EOF
#!/bin/sh
# Generated by toolchains/userspace/build.sh -- static OluxOS/musl compiler.
SYSROOT="\${OLUXOS_SYSROOT:-$SYSROOT}"
case " \$* " in
  *" -c "*|*" -S "*|*" -E "*|*" -M "*|*" -MM "*) LINK=0 ;;
  *" -r "*|*" -Wl,-r "*|*" -nostdlib "*|*" -nostartfiles "*) LINK=0 ;;
  *) LINK=1 ;;
esac
if [ \$LINK = 0 ]; then
  exec ${CROSS}gcc -nostdinc -isystem "\$SYSROOT/include" \\
    -isystem "\$(${CROSS}gcc -print-file-name=include)" "\$@"
fi
exec ${CROSS}gcc -static -nostdlib -nostdinc -isystem "\$SYSROOT/include" \\
  -isystem "\$(${CROSS}gcc -print-file-name=include)" \\
  "\$SYSROOT/lib/crt1.o" "\$SYSROOT/lib/crti.o" "$(dirname "$libgcc")/crtbeginT.o" \\
  "\$@" -L"\$SYSROOT/lib" -Wl,--start-group -lc "$libgcc" -Wl,--end-group \\
  "$(dirname "$libgcc")/crtend.o" "\$SYSROOT/lib/crtn.o"
EOF
  chmod +x "$OUT/bin/oluxos-cc"
  for t in ar ranlib strip objcopy objdump readelf nm; do
    ln -sf "$(command -v "${CROSS}$t")" "$OUT/bin/oluxos-$t"
  done
}

# Linux-ABI headers (musl has none); refreshed on every build.
install_linux_headers() {
  rm -rf "$SYSROOT/include/linux"
  cp -r "$REPO_ROOT/toolchains/userspace/linux-headers/linux" "$SYSROOT/include/"
}

build_busybox() {
  [ -f "$SYSROOT/lib/libc.a" ] || build_musl
  install_linux_headers
  write_wrapper
  verify "$BUSYBOX_TARBALL" "$BUSYBOX_SHA256"
  log "building busybox $BUSYBOX_VERSION"
  local src="$WORK/busybox-$BUSYBOX_VERSION"
  rm -rf "$src"
  tar -xjf "$BUSYBOX_TARBALL" -C "$WORK"
  if [ -d "$BUSYBOX_PATCHES" ]; then
    for p in "$BUSYBOX_PATCHES"/*.patch; do
      [ -e "$p" ] || continue
      log "  applying $(basename "$p")"
      patch -d "$src" -p1 -s <"$p"
    done
  fi
  cp "$BUSYBOX_CONFIG" "$src/.config"
  (
    cd "$src"
    local mk=(ARCH=arm64 CROSS_COMPILE="${CROSS}" CC="$OUT/bin/oluxos-cc"
              HOSTCC="${HOSTCC:-cc}" KBUILD_BUILD_TIMESTAMP="@$SOURCE_DATE_EPOCH"
              KBUILD_BUILD_USER=oluxos KBUILD_BUILD_HOST=oluxos)
    { yes '' || true; } | make "${mk[@]}" oldconfig >/dev/null
    make "${mk[@]}" -j"$JOBS" busybox busybox.links >"$WORK/busybox-build.log" 2>&1 \
      || { tail -40 "$WORK/busybox-build.log" >&2; die "busybox build failed"; }
  )
  cp "$src/busybox.links" "$OUT/bin/busybox.links"
  cp "$src/busybox_unstripped" "$OUT/bin/busybox.debug"
  "${CROSS}strip" -o "$OUT/bin/busybox" "$src/busybox_unstripped"
  log "busybox: $OUT/bin/busybox ($(wc -c <"$OUT/bin/busybox") bytes)"
}

build_dropbear() {
  [ -f "$SYSROOT/lib/libc.a" ] || build_musl
  install_linux_headers
  write_wrapper
  verify "$DROPBEAR_TARBALL" "$DROPBEAR_SHA256"
  log "building dropbear $DROPBEAR_VERSION"
  local src="$WORK/dropbear-$DROPBEAR_VERSION"
  rm -rf "$src"
  tar -xjf "$DROPBEAR_TARBALL" -C "$WORK"
  cat >"$src/localoptions.h" <<'OPTS'
/* OluxOS: key-based and password logins, no X11 or agent forwarding. */
#define DROPBEAR_X11FWD 0
#define DROPBEAR_SVR_AGENTFWD 0
#define DROPBEAR_CLI_AGENTFWD 0
#define DEFAULT_PATH "/usr/bin:/bin"
#define DEFAULT_ROOT_PATH "/usr/sbin:/usr/bin:/sbin:/bin"
OPTS
  (
    cd "$src"
    CC="$OUT/bin/oluxos-cc" AR="${CROSS}ar" RANLIB="${CROSS}ranlib" \
      ./configure --host=aarch64-linux-musl --disable-zlib --enable-static --disable-lastlog \
      --disable-utmp --disable-utmpx --disable-wtmp --disable-wtmpx --disable-pututline \
      --disable-pututxline --disable-harden >"$WORK/dropbear-configure.log" 2>&1 \
      || { tail -30 "$WORK/dropbear-configure.log" >&2; die "dropbear configure failed"; }
    make -j"$JOBS" PROGRAMS="dropbear dropbearkey dbclient scp" MULTI=1 STATIC=1 \
      >"$WORK/dropbear-build.log" 2>&1 \
      || { tail -40 "$WORK/dropbear-build.log" >&2; die "dropbear build failed"; }
  )
  "${CROSS}strip" -o "$OUT/bin/dropbearmulti" "$src/dropbearmulti"
  log "dropbear: $OUT/bin/dropbearmulti ($(wc -c <"$OUT/bin/dropbearmulti") bytes)"
}

case "$TARGET" in
  musl) build_musl; write_wrapper ;;
  busybox) build_musl; build_busybox ;;
  dropbear) build_musl; build_dropbear ;;
  all) build_musl; build_busybox; build_dropbear ;;
esac
log "done (sysroot: $SYSROOT)"
